/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Baitap1;

import javax.swing.JOptionPane;
import javax.swing.ListModel;
import java.util.List;
import java.util.ArrayList;

/**
 *
 * @author luan
 */
public class bai4 extends javax.swing.JFrame {

    /**
     * Creates new form bai4
     */
    public bai4() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jListTrai = new javax.swing.JList<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        sphai = new javax.swing.JButton();
        allphai = new javax.swing.JButton();
        strai = new javax.swing.JButton();
        alltrai = new javax.swing.JButton();
        btthem = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jListPhai = new javax.swing.JList<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Đăng kí môn học");

        jListTrai.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Bóng Chuyền", "Cầu Lông", "Bơi", "Võ", "Bóng Đá", "Chạy", " " };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(jListTrai);

        jLabel1.setText("DS Môn thể thao");

        jLabel2.setText("Môn yêu thích");

        sphai.setText(">");
        sphai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sphaiActionPerformed(evt);
            }
        });

        allphai.setText(">>");
        allphai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                allphaiActionPerformed(evt);
            }
        });

        strai.setText("<");
        strai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                straiActionPerformed(evt);
            }
        });

        alltrai.setText("<<");
        alltrai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                alltraiActionPerformed(evt);
            }
        });

        btthem.setText("+");
        btthem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btthemActionPerformed(evt);
            }
        });

        jScrollPane2.setViewportView(jListPhai);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btthem)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 102, Short.MAX_VALUE)
                        .addComponent(jScrollPane1)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(allphai, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(alltrai, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(strai, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(sphai, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(145, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jLabel1))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(sphai)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(allphai)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(strai)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(alltrai))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btthem)
                .addContainerGap(59, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void sphaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sphaiActionPerformed
        //Lấy về model
        ListModel mTrai = jListTrai.getModel();
        ArrayList<String> arrTrai = new ArrayList<>();
        ListModel mPhai= jListPhai.getModel();
        ArrayList<String> arrPhai = new ArrayList<>();
        //lấy vị trí chọn
        int i = jListTrai.getSelectedIndex(); 
        //Xử lý danh sách trái
        for (int j=0; j<mTrai.getSize(); j++)
        {   
            String ten =mTrai.getElementAt(j).toString();
            arrTrai.add(ten);
        }
        //xóa khỏi arr  trai
        arrTrai.remove(i);
        String[] dataLeft = arrTrai.toArray(new String[0]);
        jListTrai.setListData(dataLeft);
         //Xử lý danh sách phải
        for (int z=0; z<mPhai.getSize(); z++)
        {   
            String ten =mPhai.getElementAt(z).toString();
            arrPhai.add(ten);
        }
        arrPhai.add(mTrai.getElementAt(i).toString());
        String[] dataPhai = arrPhai.toArray(new String[0]);
        jListPhai.setListData(dataPhai);
    }//GEN-LAST:event_sphaiActionPerformed

    private void allphaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_allphaiActionPerformed
        //Lấy về model
        ListModel mTrai = jListTrai.getModel();
        ListModel mPhai= jListPhai.getModel();
        ArrayList<String> arr = new ArrayList<>();
        //Xử lý danh sách phải
        for (int i=0; i<mPhai.getSize(); i++)
        {   
            String ten =mPhai.getElementAt(i).toString();
            arr.add(ten);
        }
        //Xử lý danh sách Trái
        for (int i=0; i<mTrai.getSize(); i++)
        {   
            String ten =mTrai.getElementAt(i).toString();
            arr.add(ten);
        }
        String[] data = arr.toArray(new String[0]);
        jListPhai.setListData(data);
        arr.removeAll(arr);
        data = arr.toArray(new String[0]);
        jListTrai.setListData(data);
    }//GEN-LAST:event_allphaiActionPerformed

    private void straiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_straiActionPerformed

        ListModel mTrai = jListTrai.getModel();
        ArrayList<String> arrTrai = new ArrayList<>();
        ListModel mPhai= jListPhai.getModel();
        ArrayList<String> arrPhai = new ArrayList<>();
        int i = jListPhai.getSelectedIndex();
        for (int j=0; j<mTrai.getSize(); j++)
        {   
            String ten =mTrai.getElementAt(j).toString();
            arrTrai.add(ten);
        }
        arrTrai.add(mPhai.getElementAt(i).toString());
        String[] dataTrai = arrTrai.toArray(new String[0]);
        jListTrai.setListData(dataTrai);
        for (int j=0; j<mPhai.getSize(); j++)
        {   
            String ten =mPhai.getElementAt(j).toString();
            arrPhai.add(ten);
        }
        arrPhai.remove(i);
        String[] dataPhai = arrPhai.toArray(new String[0]);
        jListPhai.setListData(dataPhai);
    }//GEN-LAST:event_straiActionPerformed

    private void alltraiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_alltraiActionPerformed
        ListModel mTrai = jListTrai.getModel();
        ListModel mPhai= jListPhai.getModel();
        ArrayList<String> arr = new ArrayList<>();
        for (int i=0; i<mTrai.getSize(); i++)
        {   
            String ten =mTrai.getElementAt(i).toString();
            arr.add(ten);
        }
        for (int i=0; i<mPhai.getSize(); i++)
        {   
            String ten =mPhai.getElementAt(i).toString();
            arr.add(ten);
        }
        String[] data = arr.toArray(new String[0]);
        jListTrai.setListData(data);
        arr.removeAll(arr);
        data = arr.toArray(new String[0]);
        jListPhai.setListData(data);
    }//GEN-LAST:event_alltraiActionPerformed

    private void btthemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btthemActionPerformed
        String Nhap = JOptionPane.showInputDialog(null,"thêm môn học mới");
        ListModel mTrai = jListTrai.getModel();
        List<String> listTrai = new ArrayList();
        for(int i=0; i<mTrai.getSize();i++ )
            listTrai.add(mTrai.getElementAt(i).toString());
        listTrai.add(Nhap);
        Object[]arrTrai = listTrai.toArray(new String[0]);
        jListTrai.setListData((String[]) arrTrai);
                
        
    }//GEN-LAST:event_btthemActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(bai4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(bai4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(bai4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(bai4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new bai4().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton allphai;
    private javax.swing.JButton alltrai;
    private javax.swing.JButton btthem;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JList<String> jListPhai;
    private javax.swing.JList<String> jListTrai;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton sphai;
    private javax.swing.JButton strai;
    // End of variables declaration//GEN-END:variables
}
